# Generated by Django 4.2.14 on 2024-08-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
